/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaceGUI;

import SourceCode.Appointment;
import SourceCode.Facility;
import SourceCode.Personnel;
import SourceCode.UtilityTools;
import SourceCode.Vaccine;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author devil
 */
public class CreateAppointmentGUI extends javax.swing.JFrame {
private ArrayList<Vaccine> vaccine = new ArrayList<Vaccine>();
private ArrayList<Facility> facilities = new ArrayList<Facility>();
public Personnel loggedPS;
public AppointmentGUI test;
public String location;
    /**
     * Creates new form CreateAppointmentGUI
     */
     public CreateAppointmentGUI(){
         initComponents();
     }

    public CreateAppointmentGUI(Personnel p) {
        test = new AppointmentGUI(p);
        test.setVisible(true);
        
        this.loggedPS = p;
        initComponents();
        UtilityTools u = new UtilityTools();
        vaccine = u.LoadVaccine();
        facilities = u.LoadFacilities();
        
        for(int i=0;i < facilities.size();i++){
            if(loggedPS.getFacility().equals(facilities.get(i).getFacName())){
                this.location = facilities.get(i).getFacLocation();
            }              
        }
        
        for(int i=0;i <24;i++){ //Load Time 0 - 23
            String time= Integer.toString(i);
            comboTime.addItem(time);
        }
                     
        for(int i = 0; i<vaccine.size();i++){ //Load available vaccines
            int quantity = Integer.parseInt(vaccine.get(i).getQuantity());
            if(quantity>0){
            comboVaccine.addItem(vaccine.get(i).getVaccName());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblVaccine = new javax.swing.JLabel();
        comboVaccine = new javax.swing.JComboBox<>();
        lblUserID = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        comboTime = new javax.swing.JComboBox<>();
        lblDate = new javax.swing.JLabel();
        jdateDate = new com.toedter.calendar.JDateChooser();
        comboUser = new javax.swing.JComboBox<>();
        btnDone = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("New Appointment");

        lblVaccine.setText("Vaccine");

        comboVaccine.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick a vaccine" }));

        lblUserID.setText("User ID: ");

        lblTime.setText("Time (24 hr format)");

        comboTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick a time" }));

        lblDate.setText("Date");

        comboUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pick a user", "1", "2", "3" }));

        btnDone.setText("Done");
        btnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTime)
                                    .addComponent(lblUserID)
                                    .addComponent(comboTime, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboUser, 0, 140, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblDate)
                                    .addComponent(lblVaccine)
                                    .addComponent(jdateDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(comboVaccine, 0, 140, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnback)
                            .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTime, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jdateDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboTime))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserID)
                    .addComponent(lblVaccine))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboVaccine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnDone, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnback)
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        this.dispose();
        test.dispose();
        test = new AppointmentGUI(loggedPS);
        test.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneActionPerformed
        String time = comboTime.getSelectedItem().toString();
        String date;
        String loc = this.location;
        String status = "First Dose";
        String facility = loggedPS.getFacility();
        String user = comboUser.getSelectedItem().toString();
        String vacc = comboVaccine.getSelectedItem().toString();
         UtilityTools u = new UtilityTools();
        
       if(comboTime.getSelectedIndex()==0 ||
               comboUser.getSelectedIndex()==0 ||
               comboVaccine.getSelectedIndex()==0 ||
               jdateDate.getDate()==null){
        JOptionPane.showMessageDialog(null,"There is information not selected!");
        }else if(u.isValidDate(jdateDate.getDate(),time)== false){
           JOptionPane.showMessageDialog(null,"Please select a valid date"); 
       }else{
        int input = JOptionPane.showConfirmDialog(null, "Are you sure you want to create the appointment?","",JOptionPane.OK_CANCEL_OPTION);         
        if(input ==0){
        
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");       
        date = df.format(jdateDate.getDate());    
        Appointment appt = new Appointment("0",time,date,loc,facility,status,user,vacc);
        appt.RegisterNewAppointment();
        u.UpdateVaccineQuantity("-", vacc);
        JOptionPane.showMessageDialog(null,"Appointment has been created successfully.");

        this.dispose();
        test.dispose();
        test = new AppointmentGUI(loggedPS);
        test.setVisible(true);
        }
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAppointmentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAppointmentGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDone;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> comboTime;
    private javax.swing.JComboBox<String> comboUser;
    private javax.swing.JComboBox<String> comboVaccine;
    private javax.swing.JLabel jLabel1;
    private com.toedter.calendar.JDateChooser jdateDate;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblVaccine;
    // End of variables declaration//GEN-END:variables
}
